export const teams = [
  { name: "Brasil", flag: "🇧🇷", rating: 92 },
  { name: "França", flag: "🇫🇷", rating: 91 },
  { name: "Argentina", flag: "🇦🇷", rating: 90 },
  { name: "Inglaterra", flag: "🏴", rating: 89 },
  { name: "Portugal", flag: "🇵🇹", rating: 88 },
  { name: "Espanha", flag: "🇪🇸", rating: 87 },
  { name: "Holanda", flag: "🇳🇱", rating: 86 },
  { name: "Alemanha", flag: "🇩🇪", rating: 85 },
  { name: "Itália", flag: "🇮🇹", rating: 84 },
  { name: "Croácia", flag: "🇭🇷", rating: 83 },
  { name: "Uruguai", flag: "🇺🇾", rating: 82 },
  { name: "Bélgica", flag: "🇧🇪", rating: 81 },
  { name: "Suíça", flag: "🇨🇭", rating: 80 },
  { name: "Dinamarca", flag: "🇩🇰", rating: 79 },
  { name: "EUA", flag: "🇺🇸", rating: 78 },
  { name: "México", flag: "🇲🇽", rating: 78 },
  { name: "Marrocos", flag: "🇲🇦", rating: 77 },
  { name: "Japão", flag: "🇯🇵", rating: 77 },
  { name: "Senegal", flag: "🇸🇳", rating: 76 },
  { name: "Polônia", flag: "🇵🇱", rating: 75 },
  { name: "Sérvia", flag: "🇷🇸", rating: 75 },
  { name: "Nigéria", flag: "🇳🇬", rating: 74 },
  { name: "Coreia do Sul", flag: "🇰🇷", rating: 74 },
  { name: "Austrália", flag: "🇦🇺", rating: 73 },
  { name: "Canadá", flag: "🇨🇦", rating: 73 },
  { name: "Turquia", flag: "🇹🇷", rating: 72 },
  { name: "Suécia", flag: "🇸🇪", rating: 72 },
  { name: "Equador", flag: "🇪🇨", rating: 71 },
  { name: "Peru", flag: "🇵🇪", rating: 70 },
  { name: "Colômbia", flag: "🇨🇴", rating: 70 },
  { name: "Ucrânia", flag: "🇺🇦", rating: 69 },
  { name: "Egito", flag: "🇪🇬", rating: 69 },
];

